apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: netology-rbak
  name: log-reader-binding
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: log-reader
  apiGroup: rbac.authorization.k8s.io
